# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            My Notes
tagline:          'The faintest Ink is More Powerful Than the Strongest Memory'
description:      'A website to keep track of things I am learning. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://jeel-shah.github.io/my-notes/

author:
  name:           'Jeel Shah'
  url:            https://jeel-shah.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Jeel-Shah/my-notes
